spring:
  application:
    name: service-b
server:
  port: 10102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    metadata-map:
     versions: 1,2

feign:
  hystrix:
    enabled: true

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    eureka:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000