spring:
  application:
    name: service-b
server:
  port: 20102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true

gray:
  client:
    instance:
      grayEnroll: true #是否在启动后自动注册成灰度实例
    serverUrl: http://localhost:20202 #灰度服务端的url