spring:
  application:
    name: api-gateway
server:
  port: 10301
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    eureka:
        enabled: true
zuul:
  prefix: /gateway #为zuul设置一个公共的前缀
  routes:
   api:
       path: /api/**
       serviceId: service-b
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000